#!/usr/bin/env python3
"""Generate include/cap_prop_table.hpp from OpenCV C++ header.
Zero dependency on pip cv2 - header is source of truth."""
import argparse, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent

PROP_BACKEND_FAMILIES = [
    ("DC1394","FireWire/DC1394"),("OPENNI2","OpenNI2"),("OPENNI","OpenNI"),
    ("ANDROID","Android"),("PVAPI","Pleora PVAPI"),("GIGA","Basler GigE"),
    ("INTELPERC","Intel Perceptual"),("XI","Ximea"),("V4L","V4L2"),
    ("GSTREAMER","GStreamer"),("UEYE","uEye"),("OBSENSOR","Orbbec"),
    ("ARAVIS","Aravis"),("WINRT","Windows RT"),("MSMF","MSMF"),
    ("AVFOUNDATION","AVFoundation"),("DSHOW","DirectShow"),
    ("FIREWIRE","FireWire"),("GPHOTO2","gPhoto2"),("IOS_DEVICE","iOS/AVFoundation"),
]
FAMILIES = [(None,"generic")] + PROP_BACKEND_FAMILIES
BLACKLIST = {"SETTINGS","GUID","POS_MSEC","POS_FRAMES","POS_AVI_RATIO","FRAME_COUNT"}
EXTRA_KNOWN_PROPS = [
    "CAP_PROP_AUDIO_BASE_INDEX","CAP_PROP_AUDIO_DATA_DEPTH","CAP_PROP_AUDIO_POS",
    "CAP_PROP_AUDIO_SAMPLES_PER_SECOND","CAP_PROP_AUDIO_SHIFT_NSEC",
    "CAP_PROP_AUDIO_STREAM","CAP_PROP_AUDIO_SYNCHRONIZE",
    "CAP_PROP_AUDIO_TOTAL_CHANNELS","CAP_PROP_AUDIO_TOTAL_STREAMS",
    "CAP_PROP_CODEC_EXTRADATA_INDEX","CAP_PROP_DTS_DELAY","CAP_PROP_FRAME_TYPE",
    "CAP_PROP_IMAGE_SEQ_START","CAP_PROP_LRF_HAS_KEY_FRAME","CAP_PROP_N_THREADS",
    "CAP_PROP_PTS","CAP_PROP_VIDEO_STREAM","CAP_PROP_VIDEO_TOTAL_CHANNELS",
    "VIDEOWRITER_PROP_COLOR_SPACE","VIDEOWRITER_PROP_DTS_DELAY",
    "VIDEOWRITER_PROP_ENABLE_ALPHA","VIDEOWRITER_PROP_KEY_FLAG",
    "VIDEOWRITER_PROP_KEY_INTERVAL","VIDEOWRITER_PROP_PTS",
    "VIDEOWRITER_PROP_RAW_VIDEO",
]

def fam_idx(short):
    for i,(token,_) in enumerate(FAMILIES):
        if i==0: continue
        if token and short.startswith(token): return i
    return 0

def parse_header(path):
    txt = path.read_text(errors="ignore")
    props=[]; seen=set()
    for m in re.finditer(r'CAP_PROP_([A-Z0-9_]+)\s*=\s*(-?\d+)', txt):
        name=m.group(1)
        if name.startswith("CV__"): continue
        full=f"CAP_PROP_{name}"
        if full in seen: continue
        seen.add(full); props.append({"name":name,"pid":int(m.group(2))})
    props.sort(key=lambda x:x["pid"])
    writers=[]; seen_w=set()
    for m in re.finditer(r'VIDEOWRITER_PROP_([A-Z0-9_]+)\s*=\s*(-?\d+)', txt):
        name=m.group(1)
        if name.startswith("CV__"): continue
        full=f"VIDEOWRITER_PROP_{name}"
        if full in seen_w: continue
        seen_w.add(full); writers.append((full,int(m.group(2))))
    writers.sort(key=lambda x:x[1])
    return props, writers

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--header",required=True)
    ap.add_argument("--out",required=True)
    a=ap.parse_args()
    hdr=pathlib.Path(a.header)
    if not hdr.is_file(): sys.exit(f"header not found: {hdr}")
    props,writers=parse_header(hdr)
    lines=["#pragma once",
           "// Generated by gen_cap_prop_table_from_header.py - DO NOT EDIT",
           f"// Source: {hdr.name} (absolute path omitted for relocatability)",
           "#include <cstddef>","","namespace camprops {","",
           "enum Fam : int {"]
    for i,(_,label) in enumerate(FAMILIES):
        lines.append(f"  FAM_{i} = {i},  // {label or 'generic'}")
    lines += ["};","",f"static const char* FAMILY_LABELS[] = {{"] 
    lines += [f'  "{l or "generic"}",' for _,l in FAMILIES] + ["};"]
    lines += ["static const char* FAMILY_TOKENS[] = {"]
    lines += [f'  "{t or ""}",' for t,_ in FAMILIES] + ["};",""]
    lines.append("struct PropEntry { const char* name; int pid; int fam; bool no_set; };")
    lines.append("static const PropEntry PROP_TABLE[] = {")
    for e in props:
        ns="true" if e["name"] in BLACKLIST else "false"
        lines.append(f'  {{"CAP_PROP_{e["name"]}", {e["pid"]}, {fam_idx(e["name"])}, {ns}}},')
    lines += ["};", "static const size_t PROP_TABLE_N = sizeof(PROP_TABLE)/sizeof(PROP_TABLE[0]);", "",
              "struct WriterProp { const char* name; int pid; };",
              "static const WriterProp WRITER_PROPS[] = {"]
    for n,pid in writers:
        lines.append(f'  {{"{n}", {pid}}},')
    lines += ["};", "static const size_t WRITER_PROPS_N = sizeof(WRITER_PROPS)/sizeof(WRITER_PROPS[0]);", ""]
    for n in EXTRA_KNOWN_PROPS:
        lines += [f"#ifdef {n}", f'  {{"{n}", {n}, {fam_idx(n[len("CAP_PROP_"):] if n.startswith("CAP_PROP_") else "")}, true}},', "#endif"]
    lines += ["", "}  // namespace camprops"]
    out=pathlib.Path(a.out); out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text("\n".join(lines)+"\n",encoding="utf-8")
    print(f"wrote {out} (props={len(props)}, writer={len(writers)})")

if __name__=="__main__": main()
